# Generated by Django 3.0.8 on 2021-06-22 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0003_auto_20210622_1516"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MenuOption",
            new_name="Option",
        ),
    ]
