# Generated by Django 3.0.8 on 2021-06-22 20:40

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0004_auto_20210622_1517"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="menu_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
