# Generated by Django 3.0.8 on 2021-06-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="option",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
