# Generated by Django 3.0.8 on 2021-06-22 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_auto_20210622_1603"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="picture",
        ),
    ]
